name: main taski workflow

on:
  push:
    branches:
      - main
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - name: print project tree
        run: tree .